version: '3.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Sagan
      MYSQL_USER: root
      MYSQL_PASSWORD: Sagan
      MYSQL_DATABASE: blog_pessoal

    networks:
      - generation-network
      
  blogpessoal-api:
    restart: always
    build: ./blogPessoal-api
    working_dir: /blogPessoal-api
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./blogPessoal-api:/blogPessoal-api
      - ~/.m2:/root/.m2
    ports: 
      - "9000:8080"
    command: mvn clean spring-boot:run
    links: 
      - db
    depends_on: 
      - db
    networks:
      - generation-network
networks:
    generation-network:
        driver: bridge