version: '2.4'
service:
  db:
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: aways
    build: 
       context: .
       dockerfile: Dockerfile
     environment: 
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: Sagan
       MYSQL_USER: root
       MYSQL_PASSWORD: Sagan
       MYSQL_DATABASE: blog_pessoal

    network:
      - generation-network
      
  blogpessoal-api:
    restart: aways
    build: ./blogpessoal-api
    working_dir: /blogpessoal-api
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./blogpessoal-api:/blogpessoal-api
      - ~/.m2:/root/.m2
    ports: 
      - "9000:8080"

    network:
      - generation-network

networks:
    generation-network:
        driver: bridge